### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by yoshson** [feinheit/feincms3-cookiecontrol#1]
@matthiask

Grundsätzlich wäre das Projekt aus meiner Sicht soweit, dass man es in einer **0.0.1 Version paketieren** könnte, grad weil's dann einfacher ist zu integrieren. Je nachdem wie aber die anderen Issues eingeschätzt werden, kann man die vorher noch auflösen.

**Comment by matthiask** [comment]
```
./setup.py sdist bdist_wheel
twine upload dist/*
```

Mit folgender Konfiguration:
![image](https://user-images.githubusercontent.com/2627/133313307-02518ead-739f-4ede-8c3e-11c7aca9a2ea.png)

Das wärs :)

**Comment by matthiask** [comment]
Bzw. was ich immer vorher noch mache:
```
git commit -m "feincms3-cookiecontrol 0.0.1" (--allow-empty)
git tag -m "feincms3-cookiecontrol 0.0.1" 0.0.1
```
und dann
```
git push --all
git push --tags
```
(Ja, muss offenbar separat ausgeführt werden. Ich weiss auch nicht weshalb 😂)

**Comment by matthiask** [comment]
@yoshson Was meinst Du, bereit für ein Release? Ein 0.0.1 ist ja nix grosses, aber immerhin...

**Comment by matthiask** [comment]
... ich kann sonst auch ein Release machen und Dich nachher einladen auf PyPI. Oder umgekehrt. Mein PyPI Username ist "matthiask".

Würde Dir aber gerne die Ehre überlassen, ein PyPI Paket zu veröffentlichen :-)

**Comment by yoshson** [comment]
Ich mach grad ^^. Es ist mir eine Ehre :P

**Comment by yoshson** [comment]
https://pypi.org/project/feincms3-cookiecontrol/0.0.1/

🥳
