### ISSUE TITLE
Lesbarkeit Checkboxes

### ISSUE THREAD

**Issue by nada** [feinheit/feincms3-cookiecontrol#14]
Die lesbarkeit der Checkboxes ist nicht ideal. 
Eine zusätzliche visuelle Rückmeldung wie Kreuzchen / Häckchen fände ich gut. Somit wöre der gewählte Status besser lesbar.

**Comment by matthiask** [comment]
![image](https://user-images.githubusercontent.com/2627/144272031-1a15c484-3cab-402d-ba44-396363865d24.png)

Ist das noch aktuell? Ich finde nicht, und schliesse mal. Bitte unbedingt wieder öffnen, wenn Du dies anders siehst @nada
