### ISSUE TITLE
Use cookie information in BE when providing resources

### ISSUE THREAD

**Issue by yoshson** [feinheit/feincms3-cookiecontrol#2]
@matthiask

Im Moment werden im Falle von User-Einwilligungen entsprechende Cookies gesetzt. Die werden aber nur im Frontend ausgewertet. Das kann und sollte vielleicht aber sogar im Backend geschehen. Dadurch lässt sich das Tool deutlich kleiner gestalten. Gerade bei vielen CookieCategories und Skripten ist das JSON viel grösser als es eigentlich sein müsste.

**Comment by matthiask** [comment]
Laut gedacht (Papierkorb). Ich frage mich... könnten wir nicht vollständig auf das Inject-Ding verzichten? Wenn jemand zu den Cookies zustimmt, wären die Skripte halt erst beim nächsten Pageload drin, ja. Wäre das ein grosses Problem?

**Comment by yoshson** [comment]
Fänd ich auch schöner, aber für SPAs wärs ungünstig.

**Comment by matthiask** [comment]
> Fänd ich auch schöner, aber für SPAs wärs ungünstig.

Ah stimmt. Ja, das machts zu einem no go.

**Comment by matthiask** [comment]
Sorry, ich führe kurz aus. Wenn jemand "essentials" annimmt, reloaded, und dann doch "analytics" hinzufügt, dann müssen die analytics Skripte im JSON drin sein. Auch wenn das Cookie existiert. 

(Ich behaupte jetzt mal, auf die paar wenigen hundert Bytes kommts nicht an, auch wenn ich selbst gerne Code Golf habe.)
