### ISSUE TITLE
Möglichkeit den Revoke Button zu verbergen

### ISSUE THREAD

**Issue by mo-we** [feinheit/feincms3-cookiecontrol#22]
Wäre es möglich, eine Einstellung zu haben, die den Revoke-Button versteckt?

Man müsste auch den z-index sehr hoch stellen, damit er auf der Hosting-Seite drüberliegt.

![image](https://user-images.githubusercontent.com/58986818/146340162-0696278d-3c6f-43b1-add5-0a697cf7b92c.png)

**Comment by matthiask** [comment]
Was ist das für eine Seite?

**Comment by mo-we** [comment]
Enersuisse, ich habe den revoke versteckt. Ich weiss gar nicht, braucht es diesen zwingend?

**Comment by matthiask** [comment]
Ah, https://github.com/feinheit/enersuisse.ch/commit/20c5d5eb316f3a3fc5e9ed323eacb1c91b524e4c

Ja, den brauchts. Aber zB nur auf der Datenschutz-Seite.

**Comment by mo-we** [comment]
Also auf dieser Seite müsste der Button erscheinen: https://enersuisse.ch/de/datenschutz/ ?

**Comment by matthiask** [comment]
@mo-we Schau hier: https://github.com/feinheit/enersuisse.ch/commit/37008cf0483a3c22655ab4a369eb5633a0921e8a

**Comment by mo-we** [comment]
Super! Aber heisst das man müsste bei einer Hosting-Seite die Datenschutz-Seite immer statisch angeben?

**Comment by matthiask** [comment]
Stand jetzt ist das so.
