### ISSUE TITLE
Simplified Panel

### ISSUE THREAD

**Issue by yoshson** [feinheit/feincms3-cookiecontrol#24]
Durch die Beschäftigung mit der Cookie Thematik und mit der generellen Unzufriedenheit, dass all zu viel Template im Javascript gemacht wird, hat mich ein Cookie-Banner neulich begeistert.

I.d.R. wird das Panel so konfiguriert, dass (egal welcher Input kommt) entweder die Essentiellen oder die Analyse-Cookies eingebunden werden. Mir ist kein Fall bekannt wo eine weitere Einteilung der Kategorien gewünscht wäre. Da sowieso ein Tag-Manager-Skript eingebunden ist, wäre es vermutlich auch viel Aufwand.

In allen Fällen wäre es also genau so sinnvoll, wenn man ein Banner einrichtet in dem man
1. Aller Verarbeitung personenbezogener Daten widersprechen kann, oder
2. die Analyse akzeptiert.

Dazu kommt, dass die Informationen über den Einsatz von Cookies und die genauen Daten der Analysedienste oder Dritten auf der Strecke bleiben, weil man auf dem Panel sehr eingeschränkt ist. Ich überlege also gerade, ob man nicht sinnvollerweise
3. eine eigene Seite anbietet, die Informationen zu den cookie-Kategorien bietet (Standardmässig die Datenschutzseite).

Das ganze Templating und Styling des Panels würde damit aus dem Markup draussen sein. Nur die Skripte und einige Texte für das Banner würden benötigt. Ich frage mich gerade ob ich was übersehen habe, oder ob das einfach keine Nachteile bringen würde. Vorteile wären also:
- Besucher*innen können einfacher allem widersprechen
- erhalten mehr detail-Infos zu den Cookies
- Das Markup ist kleiner
- Viel weniger Support fürs Styling nötig.
- und eigentlich auch: Die Datenschutzseite ist quasi automatisch mit den Infos aus den Cookie-Kategorien befüllt.

**Comment by matthiask** [comment]
Ich finde die Gedanken sehr interessant. Es stimmt, wir brauchen meist sowieso nur zwei Kategorien. Von daher scheint es eigentlich zu kompliziert.

Es könnte aber schon den Fall geben, wo es essentielle Cookies gibt, analyse-Cookies (standardmässig aktiviert im Control Panel) und zB remarketing-Cookies (standardmässig deaktiviert im Control Panel). Oder vielleicht auch den Fall, wo es zwar nicht um Cookies geht aber um Fonts, wo essentiell, fonts und analyse die drei Kategorien sein könnten. Ich kann mir vorstellen, dass die Flexibilität im Prinzip schon gut wäre, und wir sie wünschenswert finden wenn die Datenverarbeitungs-Katalogisierung bei uns etwas weiter fortgeschritten ist.

---

Ansonsten sehe ich noch die folgenden Punkte, welche evtl. gegen ein eingebundenes Control Panel auf der Datenschutz-Seite sprechen könnten:

- wir müssen das Formular-Markup weiter standardisieren, wenn wir das Styling der Website wiederverwenden wollen
- für die Konfiguration der Cookies navigiert man weg von der aktuellen Seite
