### ISSUE TITLE
no dark patterns

### ISSUE THREAD

**Issue by yoshson** [feinheit/feincms3-cookiecontrol#25]
I fear we use "dark patterns" - stupid term - to nudge users to consent to the usage of tracking cookies. This might be a problem for GDPR compliance.

We need a third button "accept only essential cookies" or "deny all" with the same styling and level of "accept all".

**Comment by matthiask** [comment]
That may be the case. I'm concerned more about the value of the `RECOMMENDED` setting https://github.com/feinheit/feincms3-cookiecontrol/blob/e4df36182d3ce4fb72b640a0bf9d01b4babeabff/feincms3_cookiecontrol/models.py#L66

I think pre-selecting categories is worse than having to click two times to reject tracking cookies. However, if we 1. remove the `RECOMMENDED` option and 2. only ever have essential and tracking cookies (What else is there anyway? "performance" Cookies maybe, but does it really matter whether data is collected by e.g. Sentry or Google? There's a difference of course but from a legal point of view it probably doesn't make any.) I wonder if there's any point keeping the settings panel around or if we should reduce feincms3-cookiecontrol to strictly the banner with an explanatory text, two buttons (accept all, reject non-essential) and the injection code. Maybe we could even also remove the `inject_else` field to simplify the CMS. After all, has `inject_else` ever been used anywhere?

**Comment by yoshson** [comment]
> I wonder if there's any point keeping the settings panel around or if we should reduce feincms3-cookiecontrol to strictly the banner with an explanatory text, two buttons (accept all, reject non-essential) and the injection code.
That would drastically reduce the setup 👍.

> After all, has inject_else ever been used anywhere?
No. I thought there was a way in GTM to handle rejections, but in the end, data would be sent to google anyway, which probably is a violation of the users decision.

**Comment by matthiask** [comment]
Twitter:
![image](https://user-images.githubusercontent.com/2627/171416889-c5635f48-236c-460d-8c7f-2bc9552c01ac.png)
