### ISSUE TITLE
Modus: "Wir tracken nicht"

### ISSUE THREAD

**Issue by matthiask** [feinheit/feincms3-cookiecontrol#28]
Macht evtl. wenig Sinn, weil das f3cc die ganzen Script Injection Geschichten drin hat...

**Comment by yoshson** [comment]
Ich würde das in ein eigenes Packet schieben. Das Panel brauchen wir im Fall vom MV nicht, weil das "tracking" über plausible gemacht wird.

**Comment by matthiask** [comment]
Meine Überlegung war nur, dass die Anzeige des Banners und das Cookie, womit das Banner für eine längere Zeit versteckt wird dieselbe ist für beide Use Cases. Deshalb dachte ich macht es allenfalls Sinn, wegen der Wiederverwendung. Aber vielleicht auch nicht.

**Comment by yoshson** [comment]
Ich glaube du hast recht. Es macht Sinn.

Ich habe mir auch mal Gedanken zu den iframes gemacht sei es Raisenow oder Youtube. Da braucht man ein separates Einverständnis vor dem Einbinden. Grundsätzlich kann man das auch im Cookie-Panel Paket integrieren.

**Comment by yoshson** [comment]
Update: Wir zeigen ein Panel an, weil faktisch externe Elemente eingebunden werden (die Cookies setzen). Wenn kein Consent besteht, dann werden die defaultmässig nicht ausgegeben, sondern es wird extra nachgefragt.

siehe https://github.com/feinheit/feincms3-cookiecontrol/tree/ys/conscious-embedding

Wenn Constent für alle Cookies gilt, dann werden die Elemente ganz normal ausgegeben.

**Comment by yoshson** [comment]
Ah sorry, das gilt für den Kontext der aktuellen Kampagne

**Comment by matthiask** [comment]
Stimmt; d.h. den "wir tracken nicht" Fall gibts eigentlich so gut wie gar nicht, ausser es wird tatsächlich nichts getrackt UND auch keine externen Dienste angebunden (nicht mal eine Newsletter-Subscription o.ä.) und das gibts so gut wie gar nicht. Ich schliesse hier mal.
