### ISSUE TITLE
Use gettext and/or app settings for panel content instead of Pages-Mixin and DB Table

### ISSUE THREAD

**Issue by yoshson** [feinheit/feincms3-cookiecontrol#3]
@matthiask

Ich finde die Integration recht aufwändig, dafür dass eigentlich nur die Revoke-Funktion dynamisch ist. Die Komplexität würde sich, glaube ich, leicht reduzieren lassen, wenn man den Panel Content nicht auf den Pages, sondern nur in den Settings und/oder Übersetzungs-Files abfüllt.

Für den Revoke Button würde im Pages Model eine Checkbox reichen, oder man nimmt eben doch die genaue Pfad-Angabe.

**Comment by matthiask** [comment]
Hmm... für die Revoke/Modify Funktion könnten wir eigentlich auch ein Template Snippet oder so bereitstellen? Dann könnte die Funktion direkt innerhalb der Privacy Policy oder den AGB verlinkt werden?
